{
    "config": {
        "abort": {
            "already_configured": "Konto ist bereits konfiguriert",
            "reauth_successful": "Die erneute Authentifizierung war erfolgreich"
        },
        "error": {
            "invalid_auth": "Ung\u00fcltige Authentifizierung",
            "reauth_failed": "Bitte verwende denselben mydevolo-Benutzer wie zuvor."
        },
        "step": {
            "reauth_confirm": {
                "data": {
                    "password": "Passwort",
                    "username": "E-Mail / devolo-ID"
                },
                "data_description": {
                    "password": "Passwort deines mydevolo-Kontos.",
                    "username": "E-Mail-Adresse, die du f\u00fcr die Registrierung der Zentrale bei mydevolo verwendet hast."
                }
            },
            "user": {
                "data": {
                    "password": "Passwort",
                    "username": "E-Mail / devolo-ID"
                },
                "data_description": {
                    "password": "Passwort deines mydevolo-Kontos.",
                    "username": "E-Mail-Adresse, die du f\u00fcr die Registrierung der Zentrale bei mydevolo verwendet hast."
                }
            },
            "zeroconf_confirm": {
                "data": {
                    "password": "Passwort",
                    "username": "E-Mail / devolo-ID"
                },
                "data_description": {
                    "password": "Passwort deines mydevolo-Kontos.",
                    "username": "E-Mail-Adresse, die du f\u00fcr die Registrierung der Zentrale bei mydevolo verwendet hast."
                }
            }
        }
    },
    "entity": {
        "binary_sensor": {
            "button": {
                "name": "Knopf {key}"
            },
            "overload": {
                "name": "\u00dcberlast"
            }
        },
        "sensor": {
            "brightness": {
                "name": "Helligkeit"
            }
        }
    },
    "exceptions": {
        "connection_failed": {
            "message": "Die Verbindung zur devolo Home Control-Zentrale {gateway_id} konnte nicht hergestellt werden."
        },
        "invalid_auth": {
            "message": "Authentifizierung fehlgeschlagen. Bitte authentifiziere dich erneut mit deinem mydevolo-Konto."
        },
        "maintenance": {
            "message": "devolo Home Control befindet sich derzeit im Wartungsmodus."
        }
    }
}