{
    "config": {
        "abort": {
            "already_configured": "Za\u0159\u00edzen\u00ed je ji\u017e nastaveno"
        },
        "error": {
            "cannot_connect": "Nepoda\u0159ilo se p\u0159ipojit",
            "invalid_auth": "Neplatn\u00e9 ov\u011b\u0159en\u00ed",
            "timeout_connect": "Vypr\u0161el \u010dasov\u00fd limit pro nav\u00e1z\u00e1n\u00ed spojen\u00ed",
            "unknown": "Neo\u010dek\u00e1van\u00e1 chyba"
        },
        "step": {
            "user": {
                "data": {
                    "api_token": "Token API",
                    "url": "URL",
                    "verify_ssl": "Ov\u011b\u0159it certifik\u00e1t SSL"
                },
                "data_description": {
                    "api_token": "P\u0159\u00edstupov\u00fd token API pro ov\u011b\u0159ov\u00e1n\u00ed pomoc\u00ed Portaineru",
                    "url": "URL adresa va\u0161\u00ed instance Portaineru, v\u010detn\u011b portu",
                    "verify_ssl": "Zda ov\u011b\u0159ovat SSL certifik\u00e1ty. Zaka\u017ete jen v p\u0159\u00edpad\u011b, \u017ee m\u00e1te certifik\u00e1t podepsan\u00fd dr\u017eitelem."
                },
                "description": "P\u0159\u00edstupov\u00fd token si m\u016f\u017eete vytvo\u0159it v u\u017eivatelsk\u00e9m rozhran\u00ed Portaineru. P\u0159ejd\u011bte do sekce **My account > Access tokens** a vyberte volbu **Add access token**."
            }
        }
    },
    "device": {
        "unknown_container": {
            "name": "Nezn\u00e1m\u00fd kontejner"
        }
    },
    "entity": {
        "binary_sensor": {
            "status": {
                "name": "Stav"
            }
        }
    },
    "exceptions": {
        "cannot_connect": {
            "message": "P\u0159i pokusu o p\u0159ipojen\u00ed k instanci Portainer do\u0161lo k chyb\u011b: {error}"
        },
        "invalid_auth": {
            "message": "P\u0159i pokusu o ov\u011b\u0159en\u00ed do\u0161lo k chyb\u011b: {error}"
        },
        "timeout_connect": {
            "message": "P\u0159i pokusu o p\u0159ipojen\u00ed k instanci Portainer do\u0161lo k vypr\u0161en\u00ed \u010dasov\u00e9ho limitu: {error}"
        }
    }
}